### ISSUE TITLE
TypeError: Cannot set property '0' of undefined

### ISSUE THREAD

**Issue by iliasbhal** [TransitApp/gtfsNodeLib#10]
this.v is undefined

```js gtfs/helpers/import.js
// path: gtfs/helpers/import.js line 223

  for (const [index, key] of sortedKeys.entries()) {
    Object.defineProperty(GtfsRow.prototype, key, {
      get() {
        return this.v[index];
      },
      set(newValue) {
        this.v[index] = newValue; <- here. try to set index on undefined.
      },
      configurable: true,
      enumerable: true,
    });
  }
```
------------
2018-09-20 18:04:30 u:bot__ s:TRA 21631 TypeError: Cannot set property '0' of undefined
    at GtfsRowConstructor.set [as route_id] (/home/deploy/www/update-static-data/node_modules/@transit/gtfs/helpers/import.js:227:23)
    at tgtfs.forEachGtfsRoute (/home/deploy/www/update-static-data/extensions_node/NJTR.js:185:30)
    at forEachWithLog (/home/deploy/www/update-static-data/node_modules/@transit/gtfs/gtfs.js:121:7)
    at valueByKey.forEach (/home/deploy/www/update-static-data/node_modules/@transit/gtfs/helpers/logging_iterator_wrapper.js:20:5)
    at Map.forEach (native)
    at module.exports (/home/deploy/www/update-static-data/node_modules/@transit/gtfs/helpers/logging_iterator_wrapper.js:19:14)
    at forEachItem (/home/deploy/www/update-static-data/node_modules/@transit/gtfs/gtfs.js:120:5)
    at Gtfs.forEachRoute (/home/deploy/www/update-static-data/node_modules/@transit/gtfs/gtfs.js:684:28)
    at splitMainAndBergenCountyLinesDuringTranscode (/home/deploy/www/update-static-data/extensions_node/NJTR.js:180:9)
    at Object.exports.transcode.fixRouteShortNamesAndRouteKeysOnGtfs (/home/deploy/www/update-static-data/extensions_node/NJTR.js:25:3)
2018-09-20 18:04:30 u:bot__ s:TRA 21631 TypeError: Cannot set property '0' of undefined
    at GtfsRowConstructor.set [as route_id] (/home/deploy/www/update-static-data/node_modules/@transit/gtfs/helpers/import.js:227:23)
    at tgtfs.forEachGtfsRoute (/home/deploy/www/update-static-data/extensions_node/NJTR.js:185:30)
    at forEachWithLog (/home/deploy/www/update-static-data/node_modules/@transit/gtfs/gtfs.js:121:7)
    at valueByKey.forEach (/home/deploy/www/update-static-data/node_modules/@transit/gtfs/helpers/logging_iterator_wrapper.js:20:5)
    at Map.forEach (native)
    at module.exports (/home/deploy/www/update-static-data/node_modules/@transit/gtfs/helpers/logging_iterator_wrapper.js:19:14)
    at forEachItem (/home/deploy/www/update-static-data/node_modules/@transit/gtfs/gtfs.js:120:5)
    at Gtfs.forEachRoute (/home/deploy/www/update-static-data/node_modules/@transit/gtfs/gtfs.js:684:28)
    at splitMainAndBergenCountyLinesDuringTranscode (/home/deploy/www/update-static-data/extensions_node/NJTR.js:180:9)
    at Object.exports.transcode.fixRouteShortNamesAndRouteKeysOnGtfs (/home/deploy/www/update-static-data/extensions_node/NJTR.js:25:3)
Result: null
================  End  ================
2018-09-20 18:04:30 u:bot__ s:TRA 21631 ▲ End of TRA (time: 3.575s | heapIncrease: 419931160)

**Comment by iliasbhal** [comment]
@lvancraen explained me that is was an issue regarding _.cloneDeep vs GtfsRow.clone

will close this issue.
